UdemyCore_Proje/Controllers/SocialMediaController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata;

namespace UdemyCore_Proje.Controllers
{
    public class SocialMediaController : Controller
    {
        SocialMediaManager socialMediaManager = new SocialMediaManager(new EfSocialMediaDal());
        public IActionResult Index()
        {
            var values = socialMediaManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddSocialMedia()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSocialMedia(SocialMedia p)
        {
            p.Status = true;
            socialMediaManager.TAdd(p);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSocialMedia(int id)
        {
            var values = socialMediaManager.TGetByID(id);
            socialMediaManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditSocialMedia(int id)
        {
            var values = socialMediaManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditSocialMedia(SocialMedia p)
        {
            socialMediaManager.TUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

UdemyCore_Proje/Views/SocialMedia/AddSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia


@{
    ViewData["Title"] = "AddSocialMedia";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}



@using (Html.BeginForm("AddSocialMedia", "SocialMedia", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Yeni Hesap Ekleme Paneli </p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Başlık</label>
                        <input type="text" class="form-control" name="Name">
                    </div>
                    <div class="form-group">
                        <label>Url</label>
                        <input type="text" class="form-control" name="Url">
                    </div>
                    <div class="form-group">
                        <label>İkon</label>
                        <input type="text" class="form-control" name="Icon">
                    </div>
                    
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>
}

UdemyCore_Proje/Views/SocialMedia/EditSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia

@{
    ViewData["Title"] = "EditSocialMedia";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("EditSocialMedia", "SocialMedia", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Hesap Düzenleme Paneli </p>
                <form class="forms-sample">

                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x => x.SocialMediaID, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Url</label>
                        @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>İkon</label>
                        @Html.TextBoxFor(x => x.Icon, new { @class = "form-control" })
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>
}

UdemyCore_Proje/Views/SocialMedia/Index.cshtml
@using EntityLayer.Concrete
@model List<SocialMedia>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Sosyal Medya Hesapları</h4>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.SocialMediaID</td>
                                <td>@item.Name</td>
                                <td><a href="/SocialMedia/DeleteSocialMedia/@item.SocialMediaID" class="btn btn-outline-danger">Sil</a></td>
                                <td><a href="/SocialMedia/EditSocialMedia/@item.SocialMediaID" class="btn btn-outline-success">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a href="/SocialMedia/AddSocialMedia/" class="btn btn-outline-info">Yeni Hesap Ekle</a>
            </div>
        </div>
    </div>
</div>